export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_UPDATE_FAILURE = 'CART_UPDATE_FAILURE';


